import React, { useState, useCallback, useRef, useEffect } from 'react';
import ReactFlow, { 
  ReactFlowProvider, 
  Controls, 
  Background, 
  applyNodeChanges, 
  applyEdgeChanges, 
  addEdge, 
  Handle, 
  Position,
  useReactFlow
} from 'reactflow';
import 'reactflow/dist/style.css';
import { INITIAL_102_AGENTS } from './AdminAgents';

const AVAILABLE_PROJECTS = ['sdd-enterprise-dev', 'mobile-app-v2', 'legacy-migration'];

// Exact Output Artefacts generated by each Primary Agent module
export const MODULE_OUTPUT_ARTIFACTS = {
  'Requirement to Spec': ['PRD / System Specification (spec.md)'],
  'Spec to Story': ['User Stories', 'Acceptance Criteria (Gherkin)'],
  'User Stories': ['Decomposed Feature Specs', 'API Contracts'],
  'UX Wireframe': ['UI Screen Wireframes', 'Interactive Prototypes'],
  'Functional Spec': ['Business Rule Validation', 'Compliance Matrix'],
  'Tech Architecture': ['High-Level Architecture (HLD)', 'ADR Decisions'],
  'Database Design': ['ERD Schema Models', 'Physical SQL Scripts'],
  'Test Cases': ['Automated Test Suite', 'Synthetic Test Data'],
  'Traceability Matrix': ['Traceability Lineage Matrix', 'Blast Radius Report'],
  'Review Agent': ['PR Conformance Report', 'Security Audit Findings'],
  'Live Debate Boardroom': ['ARB Consensus Record', 'Gate Sign-Off Approval'],
  'Code to Spec': ['Production Source Code', 'Unit Test Suite'],
  'Evidence Ledger': ['AI Audit Trail', 'Compliance Evidence Package'],
  'Agent Registry & Security': ['RBAC Enforcement Matrix', 'Gate Security Rules'],
  'Trust, Eval & Quality': ['Quality Scorecard', 'Hallucination Evaluation Report']
};

const AgentNode = ({ id, data }) => {
  const { setNodes, setEdges } = useReactFlow();

  const onDelete = (e) => {
    e.stopPropagation();
    setNodes((nds) => nds.filter(node => node.id !== id));
    setEdges((eds) => eds.filter(edge => edge.source !== id && edge.target !== id));
  };

  const outputs = MODULE_OUTPUT_ARTIFACTS[data.label] || data.outputs || ['Generated SDLC Artefact'];

  return (
    <div className="bg-[#0b0f19] border border-slate-700/90 rounded-2xl shadow-2xl min-w-[280px] max-w-[320px] font-sans overflow-hidden transition-all hover:border-purple-500/60 group/node relative">
      
      {/* General Node Input Handle (Left Top) */}
      <Handle 
        type="target" 
        position={Position.Left} 
        id={`in-${id}`} 
        style={{ left: '-7px', top: '24px', background: '#3b82f6', width: '11px', height: '11px', border: '2px solid #0b0f19', zIndex: 30 }} 
        title="General Node Input Port"
      />

      {/* Card Header */}
      <div className="bg-gradient-to-r from-purple-950/80 via-slate-900 to-indigo-950/80 px-3.5 py-2.5 border-b border-slate-800 flex items-center justify-between">
        <div className="min-w-0 pr-2">
          <div className="flex items-center space-x-1.5">
            <span className="text-white font-bold text-[12px] tracking-tight block truncate" title={data.label}>
              {data.label}
            </span>
          </div>
          <span className="text-[10px] text-indigo-300 font-semibold font-mono flex items-center mt-0.5">
            <i className="fas fa-user-tag text-[8px] mr-1 text-indigo-400"></i>
            {data.persona}
          </span>
        </div>
        <div className="flex items-center space-x-1.5 shrink-0">
          <button 
            onClick={onDelete} 
            className="w-6 h-6 rounded-md bg-slate-800 hover:bg-rose-500/20 text-slate-400 hover:text-rose-400 transition flex items-center justify-center cursor-pointer" 
            title="Remove Agent Node"
          >
            <i className="fas fa-times text-[10px]"></i>
          </button>
        </div>
      </div>

      {/* Node Body */}
      <div className="p-3 space-y-2 text-xs bg-[#060913]">
        
        {/* EXECUTION MODE BADGE */}
        <div className="py-1 px-2.5 bg-slate-900 border border-slate-800 rounded-xl flex items-center justify-between text-[10px]">
          <span className="text-slate-400 font-semibold uppercase tracking-wider text-[9px]">Execution Mode</span>
          <span className="px-2 py-0.5 rounded-full bg-slate-800 text-purple-300 font-mono font-bold text-[9px] border border-slate-700">
            {data.autonomy || 'Bounded Execution'}
          </span>
        </div>

        {/* MAPPABLE ARTEFACTS WITH BLUE (IN) LEFT HANDLES & GREEN (OUT) RIGHT HANDLES */}
        <div className="space-y-1.5 pt-1">
          <div className="text-[9px] font-bold uppercase tracking-wider text-slate-400 flex items-center justify-between">
            <span className="flex items-center">
              <i className="fas fa-cubes text-purple-400 mr-1.5"></i>
              Module Artefacts (Inputs & Outputs)
            </span>
            <span className="text-slate-500 font-mono text-[9px]">({outputs.length})</span>
          </div>

          <div className="space-y-2">
            {outputs.map((out, idx) => (
              <div 
                key={idx} 
                className="relative flex items-center justify-between px-2.5 py-1.5 rounded-xl bg-[#0c1222] border border-slate-800 text-[10px] text-slate-200 group/art hover:border-indigo-500/60 transition"
              >
                {/* Specific Blue Input Target Handle (Left) for THIS artefact */}
                <Handle 
                  type="target" 
                  position={Position.Left} 
                  id={`in-${id}-${idx}`} 
                  style={{ left: '-13px', top: '50%', transform: 'translateY(-50%)', background: '#3b82f6', width: '12px', height: '12px', border: '2px solid #0b0f19', zIndex: 30 }} 
                  title={`Map upstream artefact as input to ${out}`}
                />

                <span className="truncate flex items-center pr-2">
                  <i className="fas fa-file-lines text-[9px] text-indigo-400 mr-1.5 shrink-0"></i>
                  <span className="truncate font-semibold text-white" title={out}>{out}</span>
                </span>

                <div className="flex items-center space-x-1 shrink-0">
                  <span className="text-[8px] font-mono text-blue-400 font-bold bg-blue-950/80 px-1 py-0.5 rounded border border-blue-800">
                    IN
                  </span>
                  <span className="text-[8px] font-mono text-emerald-400 font-bold bg-emerald-950/80 px-1 py-0.5 rounded border border-emerald-800">
                    OUT
                  </span>
                </div>

                {/* Specific Green Output Source Handle (Right) for THIS artefact */}
                <Handle 
                  type="source" 
                  position={Position.Right} 
                  id={`out-${id}-${idx}`} 
                  style={{ right: '-13px', top: '50%', transform: 'translateY(-50%)', background: '#10b981', width: '12px', height: '12px', border: '2px solid #0b0f19', zIndex: 30 }} 
                  title={`Connect ${out} output to downstream artefact input`}
                />
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
};

const nodeTypes = { agentNode: AgentNode };

const DEFAULT_PROJECT_WORKFLOWS = {
  'sdd-enterprise-dev': {
    nodes: [
      {
        id: 'node-req-spec',
        type: 'agentNode',
        position: { x: 40, y: 160 },
        data: { id: 'pa-18', label: 'Requirement to Spec', persona: 'Product Owner', autonomy: 'Generate' }
      },
      {
        id: 'node-spec-story',
        type: 'agentNode',
        position: { x: 400, y: 160 },
        data: { id: 'pa-41', label: 'Spec to Story', persona: 'Business Analyst', autonomy: 'Generate' }
      },
      {
        id: 'node-ux-wireframe',
        type: 'agentNode',
        position: { x: 770, y: 40 },
        data: { id: 'pa-54', label: 'UX Wireframe', persona: 'UX Designer', autonomy: 'Generate' }
      },
      {
        id: 'node-func-spec',
        type: 'agentNode',
        position: { x: 770, y: 340 },
        data: { id: 'pa-08', label: 'Functional Spec', persona: 'Business Analyst', autonomy: 'Validate' }
      },
      {
        id: 'node-test-cases',
        type: 'agentNode',
        position: { x: 1140, y: 190 },
        data: { id: 'pa-45', label: 'Test Cases', persona: 'QA Engineer', autonomy: 'Generate' }
      }
    ],
    edges: [
      { id: 'e-1-2', source: 'node-req-spec', sourceHandle: 'out-node-req-spec-0', target: 'node-spec-story', targetHandle: 'in-node-spec-story-0', animated: true, style: { stroke: '#10b981', strokeWidth: 2 } },
      { id: 'e-2-3', source: 'node-spec-story', sourceHandle: 'out-node-spec-story-0', target: 'node-ux-wireframe', targetHandle: 'in-node-ux-wireframe-0', animated: true, style: { stroke: '#10b981', strokeWidth: 2 } },
      { id: 'e-2-4', source: 'node-spec-story', sourceHandle: 'out-node-spec-story-1', target: 'node-func-spec', targetHandle: 'in-node-func-spec-1', animated: true, style: { stroke: '#10b981', strokeWidth: 2 } },
      { id: 'e-3-5', source: 'node-ux-wireframe', sourceHandle: 'out-node-ux-wireframe-0', target: 'node-test-cases', targetHandle: 'in-node-test-cases-0', animated: true, style: { stroke: '#10b981', strokeWidth: 2 } },
      { id: 'e-4-5', source: 'node-func-spec', sourceHandle: 'out-node-func-spec-0', target: 'node-test-cases', targetHandle: 'in-node-test-cases-1', animated: true, style: { stroke: '#10b981', strokeWidth: 2 } }
    ]
  }
};

const Sidebar = ({ nodes }) => {
  const [filterPersona, setFilterPersona] = useState('ALL');
  const onDragStart = (event, nodeType, agent) => {
    event.dataTransfer.setData('application/reactflow', nodeType);
    event.dataTransfer.setData('agentData', JSON.stringify(agent));
    event.dataTransfer.effectAllowed = 'move';
  };

  const usedAgentIds = nodes.map(n => n.data.id);
  const availableAgents = INITIAL_102_AGENTS.filter(a => {
    const isUnused = !usedAgentIds.includes(a.id);
    const matchesPersona = filterPersona === 'ALL' || a.persona === filterPersona;
    return isUnused && matchesPersona;
  });

  return (
    <div className="w-72 bg-[#0b0f19] border-r border-slate-800 flex flex-col h-full shrink-0 z-10 text-xs">
      <div className="p-4 border-b border-slate-800 bg-slate-900/30 space-y-2">
        <h3 className="text-sm font-bold text-white uppercase tracking-wider">102 Agent Palette</h3>
        <p className="text-[11px] text-slate-400">Drag agents onto the canvas</p>

        <select
          value={filterPersona}
          onChange={(e) => setFilterPersona(e.target.value)}
          className="w-full bg-[#060913] border border-slate-800 rounded-lg p-2 text-white focus:outline-none focus:border-indigo-500 cursor-pointer"
        >
          <option value="ALL">All 17 Personas Palette</option>
          {Array.from(new Set(INITIAL_102_AGENTS.map(a => a.persona))).map(p => (
            <option key={p} value={p}>{p}</option>
          ))}
        </select>
      </div>

      <div className="p-3 space-y-2 overflow-y-auto custom-scroll flex-1">
        {availableAgents.length === 0 ? (
          <div className="text-slate-500 text-xs text-center py-4 italic">No unused agents match filter</div>
        ) : (
          availableAgents.map(agent => (
            <div 
              key={agent.id} 
              className="p-2.5 bg-slate-900/60 border border-slate-700/60 rounded-xl cursor-grab hover:border-indigo-500/60 hover:bg-slate-800/80 transition flex items-center justify-between group"
              onDragStart={(event) => onDragStart(event, 'agentNode', { id: agent.id, label: agent.name, persona: agent.persona, autonomy: agent.autonomy })}
              draggable
            >
              <div className="flex items-center space-x-2.5 min-w-0">
                <div className="w-7 h-7 rounded-lg bg-purple-500/10 text-purple-400 flex items-center justify-center shrink-0">
                  <i className="fas fa-robot text-xs"></i>
                </div>
                <div className="truncate min-w-0">
                  <span className="text-[11px] font-bold text-slate-200 block truncate">{agent.name}</span>
                  <span className="text-[9px] text-slate-500 truncate block">{agent.persona}</span>
                </div>
              </div>
              <i className="fas fa-grip-vertical text-slate-600 text-[10px] shrink-0 ml-1"></i>
            </div>
          ))
        )}
      </div>
    </div>
  );
};

export default function AdminWorkflows() {
  const [selectedProject, setSelectedProject] = useState(null);
  const [nodes, setNodes] = useState([]);
  const [edges, setEdges] = useState([]);
  const [cycleError, setCycleError] = useState(false);
  const [projectMappings, setProjectMappings] = useState({});
  const reactFlowWrapper = useRef(null);
  const [reactFlowInstance, setReactFlowInstance] = useState(null);
  
  useEffect(() => {
    const saved = localStorage.getItem('sdd_project_workflows');
    if (saved) {
      try {
        setProjectMappings(JSON.parse(saved));
      } catch (e) {
        console.error(e);
      }
    }
  }, []);

  const openCanvas = (project) => {
    setSelectedProject(project);
    const existingWorkflow = projectMappings[project] || DEFAULT_PROJECT_WORKFLOWS[project];
    if (existingWorkflow) {
      setNodes(existingWorkflow.nodes || []);
      setEdges(existingWorkflow.edges || []);
    } else {
      setNodes([]);
      setEdges([]);
    }
  };

  const closeCanvas = () => {
    setSelectedProject(null);
    setNodes([]);
    setEdges([]);
  };

  const onNodesChange = useCallback(
    (changes) => setNodes((nds) => applyNodeChanges(changes, nds)),
    [setNodes]
  );
  
  const onEdgesChange = useCallback(
    (changes) => setEdges((eds) => applyEdgeChanges(changes, eds)),
    [setEdges]
  );

  const onConnect = useCallback(
    (params) => {
      const hasCycle = (source, target, currentEdges) => {
        const adj = {};
        currentEdges.forEach(edge => {
          if (!adj[edge.source]) adj[edge.source] = [];
          adj[edge.source].push(edge.target);
        });
        
        const visited = new Set();
        const stack = [target];
        
        while (stack.length > 0) {
          const curr = stack.pop();
          if (curr === source) return true;
          if (!visited.has(curr)) {
            visited.add(curr);
            const neighbors = adj[curr] || [];
            neighbors.forEach(n => stack.push(n));
          }
        }
        return false;
      };

      if (hasCycle(params.source, params.target, edges)) {
        setCycleError(true);
        return;
      }

      const newEdge = { 
        ...params, 
        id: `e-${params.source}-${params.target}-${Date.now()}`,
        animated: true,
        style: { stroke: '#10b981', strokeWidth: 2 }
      };
      setEdges((eds) => addEdge(newEdge, eds));
    },
    [edges, setEdges]
  );

  const onDragOver = useCallback((event) => {
    event.preventDefault();
    event.dataTransfer.dropEffect = 'move';
  }, []);

  const onDrop = useCallback(
    (event) => {
      event.preventDefault();

      const type = event.dataTransfer.getData('application/reactflow');
      const agentDataStr = event.dataTransfer.getData('agentData');

      if (typeof type === 'undefined' || !type || !agentDataStr) {
        return;
      }

      const agentData = JSON.parse(agentDataStr);

      setNodes((nds) => {
        if (nds.some(n => n.data.id === agentData.id)) {
          return nds;
        }
        
        const position = reactFlowInstance.screenToFlowPosition({
          x: event.clientX,
          y: event.clientY,
        });
        
        const newNode = {
          id: `node_${agentData.id}_${Date.now()}`,
          type,
          position,
          data: { ...agentData },
        };
        return nds.concat(newNode);
      });
    },
    [reactFlowInstance]
  );

  const saveWorkflow = () => {
    if (!selectedProject) return;
    
    const flow = { nodes, edges };
    const updatedMappings = { ...projectMappings, [selectedProject]: flow };
    
    setProjectMappings(updatedMappings);
    localStorage.setItem('sdd_project_workflows', JSON.stringify(updatedMappings));
    closeCanvas();
  };

  if (!selectedProject) {
    return (
      <div className="text-white h-full flex flex-col fade-in space-y-5 p-2">
        <div className="flex justify-between items-start shrink-0">
          <div>
            <h1 className="text-[28px] font-bold tracking-tight text-white flex items-center space-x-3">
              <i className="fas fa-network-wired text-indigo-400"></i>
              <span>Agent Workflow</span>
            </h1>
            <p className="text-slate-400 mt-1 text-[14px]">Define the artifact generation pipeline across 102 persona agents.</p>
          </div>
        </div>

        <div className="bg-[#0b0f19] border border-slate-800/80 rounded-2xl overflow-hidden shadow-xl">
          <div className="p-5 border-b border-slate-800/80 bg-slate-900/20">
            <h3 className="text-base font-bold text-white mb-1">Project Workflow Pipelines</h3>
            <p className="text-[12px] text-slate-400">Manage artifact generation pipelines per project.</p>
          </div>
          <div className="overflow-x-auto">
            <table className="w-full text-left border-collapse text-xs">
              <thead>
                <tr className="bg-slate-900/40 border-b border-slate-800/80 text-[10px] uppercase tracking-wider text-slate-500 font-bold">
                  <th className="py-4 px-6">Target Project</th>
                  <th className="py-4 px-6">Pipeline Status</th>
                  <th className="py-4 px-6 text-right">Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-800/80 font-sans">
                {AVAILABLE_PROJECTS.map((project) => {
                  const isConfigured = !!projectMappings[project];
                  return (
                    <tr key={project} className="hover:bg-slate-800/20 transition group">
                      <td className="py-4 px-6">
                        <span className="inline-block px-2.5 py-0.5 rounded border border-slate-700 bg-slate-800/50 text-slate-300 text-[11px] font-mono font-semibold">
                          <i className="fas fa-cubes mr-1.5 text-slate-500"></i>
                          {project}
                        </span>
                      </td>
                      <td className="py-4 px-6">
                        {isConfigured ? (
                          <span className="inline-flex items-center space-x-1.5 text-emerald-400 text-[12px] font-semibold">
                            <i className="fas fa-check-circle"></i>
                            <span>Configured</span>
                          </span>
                        ) : (
                          <span className="inline-flex items-center space-x-1.5 text-slate-500 text-[12px] italic">
                            <i className="fas fa-exclamation-circle text-[10px]"></i>
                            <span>Not Configured</span>
                          </span>
                        )}
                      </td>
                      <td className="py-4 px-6 text-right">
                        <button 
                          onClick={() => openCanvas(project)}
                          className="bg-indigo-600/10 hover:bg-indigo-600/20 border border-indigo-500/20 text-indigo-400 hover:text-indigo-300 px-4 py-1.5 rounded-lg text-[12px] font-semibold transition flex items-center space-x-2 ml-auto cursor-pointer"
                        >
                          <i className={`fas ${isConfigured ? 'fa-edit' : 'fa-plus'}`}></i>
                          <span>{isConfigured ? 'Edit Workflow' : 'Define Workflow'}</span>
                        </button>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="text-white h-full flex flex-col fade-in min-h-[600px] p-2 space-y-4">
      {/* Header */}
      <div className="flex justify-between items-center shrink-0">
        <div className="flex items-center space-x-3">
          <button onClick={closeCanvas} className="text-slate-500 hover:text-white transition cursor-pointer text-lg">
            <i className="fas fa-arrow-left"></i>
          </button>
          <h1 className="text-xl font-bold tracking-tight text-white flex items-center space-x-2">
            <span>{selectedProject} Workflow Canvas</span>
          </h1>
        </div>
        <div className="flex space-x-3">
          <button 
            onClick={saveWorkflow}
            className="bg-emerald-600 hover:bg-emerald-500 text-white font-bold py-2 px-4 rounded-xl transition flex items-center space-x-2 text-xs cursor-pointer shadow-lg"
          >
            <i className="fas fa-save"></i>
            <span>Save Workflow</span>
          </button>
        </div>
      </div>

      {/* Editor Area */}
      <div className="flex-1 bg-[#060913] border border-slate-800 rounded-2xl overflow-hidden shadow-xl flex relative min-h-[500px]">
        <ReactFlowProvider>
          <Sidebar nodes={nodes} />
          <div className="flex-1 h-full relative" ref={reactFlowWrapper}>
            <ReactFlow
              nodes={nodes}
              edges={edges}
              onNodesChange={onNodesChange}
              onEdgesChange={onEdgesChange}
              onConnect={onConnect}
              onInit={setReactFlowInstance}
              onDrop={onDrop}
              onDragOver={onDragOver}
              nodeTypes={nodeTypes}
              fitView
              className="bg-[#03050a]"
            >
              <Background color="#334155" gap={20} size={1.5} />
              <Controls className="bg-slate-900 border-slate-700 fill-slate-300" />
            </ReactFlow>
          </div>
        </ReactFlowProvider>
      </div>

      {/* Cycle Detection Modal */}
      {cycleError && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/70 backdrop-blur-sm">
          <div className="bg-[#0c1222] border border-rose-500/30 rounded-2xl w-full max-w-md p-6 shadow-2xl space-y-4 text-xs">
            <h3 className="text-base font-bold text-white flex items-center text-rose-400">
              <i className="fas fa-exclamation-triangle mr-2"></i> Cyclic Dependency Detected
            </h3>
            <p className="text-slate-300">
              Action blocked. Connecting this agent creates a cyclic loop where an agent output depends on itself.
            </p>
            <div className="flex justify-end pt-2 border-t border-slate-800">
              <button 
                onClick={() => setCycleError(false)}
                className="bg-slate-800 hover:bg-slate-700 text-white px-4 py-2 rounded-lg font-semibold cursor-pointer"
              >
                Acknowledge
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
